name: Build

on: [ push ]

jobs:
  build_and_test:
    name: IBConverter
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - uses: actions/upload-artifact@v3
        with:
          name: IBConverter-Linux
          path: target/release/IBConverter*
